[project]
name = "freevps-reminder"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "discord.py>=1.0.7",
    "python-dotenv>=1.1.1",
    "rich>=14.1.0",
]
